### PR TITLE
Add known issue to MySQL 2.9.0 release notes

### PR DESCRIPTION
**Pull request by ssapra**
We should also add this known issue for all patches of 2.7.x and 2.8.x.

We have not released any patches that fix this yet.

[#174431087](https://www.pivotaltracker.com/story/show/174431087)

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @ssapra.

**Comment by jncd** [comment]
@ssapra 
Is it appropriate to add this to the 2.7 release?

PivNet says that MySQL v2.7 isn't compatible with TAS v2.10...
And the KI says that this issue is only for TAS v2.10.
Screen Shot 2020-08-31 at 9 25 26 AM

**Comment by ssapra** [comment]
@jncd This is a different multi-site Known Issue that is not related to TAS v2.10. This one is applicable to MySQL 2.7.x and 2.8.x (I mentioned it in the original comment).

**Comment by jncd** [comment]
Doh! Thank you! (Different partial, different KI.)
I'm adding this uppercase KI to 2.8 and 27 and pushing those to production.

**Pull request merged**
