### PR TITLE
Data loss warning & flush privileges step

### PR DESCRIPTION
**Pull request by danjahnerCF**
@menicosia Change to docs to flush privilege cache after restore. Also, a data loss warning (may be redundant).

### CODE REVIEW

**Comment by menicosia** [comment]
@danjahnerCF Sorry, would you mind re-basing and submitting a PR based on the `develop` branch, per our [CONTRIBUTING.md](CONTRIBUTING.md) instructions?

**Comment by danjahnerCF** [comment]
Confusion ahead. Checked docs-mysql and that doesn't have a develop branch. Checked cf-mysql-release/docs on develop and it doesn't have a file for the backup instructions. What am I missing?

**Comment by jbheron** [comment]
Docs team will wait for input from @menicosia for this item, per his request.

**Comment by menicosia** [comment]
Thanks @danjahnerCF, @jbheron!

**Pull request merged**
