### PR TITLE
monitor: Remove indicators protocol

### PR DESCRIPTION
**Pull request by ohkyle**
- we got rid of this in the product
- should apply to all versions we support (2.10, 3.0, 3.1, 3.2, 3.3)

[#187486114](https://www.pivotaltracker.com/story/show/187486114)

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by anita-flegg** [comment]
Hi @ohkyle , I will get to this on Mon or Tues, OK? I am still fighting my way through the kb references that will disappear on Monday.

**Comment by ohkyle** [comment]
> Hi @ohkyle , I will get to this on Mon or Tues, OK? I am still fighting my way through the kb references that will disappear on Monday.

Hey @anita-flegg no worries. The team is planning on releasing in the next week or so. This PR should be merged before the team releases within the next week.

**Review by anita-flegg — APPROVED** [review]
Looks good to me.

**Comment by anita-flegg** [comment]
Hi @ohkyle , This change was already in all the other branches.
The only additional thing I did was to remove a ref to the deleted section earlier in the topic.

**Pull request merged**
